MOS: SPC700: Emit MOV imag8, immediate instructions.
llvm-mos/llvm-mos pull request #448
Opened 2024-02-24 19:16 UTC by asiekierka

As with every logical instruction variant added, this involves a slightly annoying set of subtarget if-checks. However, being able to store an immediate in an imaginary register directly should be rather useful.

2024-02-24 19:22 UTC, asiekierka commented
Before this is merged, though, I'd like to step back for a second and consider if there's a better way of doing this. This is because the SPC700 extends a lot of opcodes in this manner. In addition to loads/stores, ADC, SBC, CMP, AND, OR, EOR all now receive `Imag8, Imag8` and `Imag8, i8imm` variants, thus widening their register classes from `Ac, imm8` and `Ac, Imag8` (or GPR for `CMP`) to `AImag8, imm8` and `AImag8, Imag8` respectively.

2024-02-25 01:31 UTC, johnwbyrd commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LoImm = Builder.buildInstr(LdImm, {S8}, {}).add(MI.getOperand(1));
Is there a reason these LdImm constants have been taken out of the MOS namespace?

2024-02-25 01:41 UTC, johnwbyrd requested changes
Thank you for your always clean and well considered change requests.  Comments inline.  If you strongly disagree, we could go ahead.

2024-02-25 01:41 UTC, johnwbyrd commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LoImm = Builder.buildInstr(LdImm, {S8}, {}).add(MI.getOperand(1));
Is there a reason that the LdImm constant was taken out of the MOS namespace?

2024-02-25 01:41 UTC, johnwbyrd commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto HiImm = Builder.buildInstr(LdImm, {S8}, {}).add(MI.getOperand(1));
Same question as above.

2024-02-25 01:41 UTC, johnwbyrd commented on llvm/lib/Target/MOS/MOSInstrInfo.h
> +  void expandLDImm16SPC700(MachineIRBuilder &Builder) const;
I don't question the implementation concept, but I am concerned that the specific naming that you've chosen to burn into the API might become invalid if a future processor elects to use the same addressing mode.  Consider renaming to LDImm16Imag8Imm, or something that you consider to be more descriptive and less processor specific.  Hopefully changing this would be a single editor operation and not too painful.

2024-02-25 01:41 UTC, johnwbyrd commented on llvm/lib/Target/MOS/MOSMCInstLower.cpp
> +    if (MI->getOpcode() == MOS::LDImmSPC700) {
As above.  Consider divorcing the particular relocation from that specific processor (in name only), thus making it a little more generic.

2024-02-25 01:41 UTC, johnwbyrd commented on llvm/test/CodeGen/MOS/instruction-selector-ir-spc700.mir
> +---
Thank you for creating this detailed test suite, I'll have to let @mysterymath comment on it.

2024-02-25 01:41 UTC, johnwbyrd commented on llvm/test/CodeGen/MOS/postrapseudos-spc700.mir
> +---
Thank you for your always clean and well-considered change requests!

2024-02-25 05:13 UTC, mysterymath commented on llvm/lib/Target/MOS/MOSInstrInfo.cpp
> +void MOSInstrInfo::expandLDImm16SPC700(MachineIRBuilder &Builder) const {
This is intrinsically similar enough to LDImm16 that it should be more maintainable to have one implementation that switches out the differences by examining the opcode.

2024-02-25 05:13 UTC, mysterymath commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LdImm = STI.hasSPC700() ? MOS::LDImmSPC700 : MOS::LDImm;
It seems like a buildLDImm abstraction might pull a lot of weight in the instruction selector; it should be possible to factor out the SPC700 vs others logic into one place. The difference doesn't affect the logical arguments of the LDImm16, only the scratch register.

2024-02-25 05:13 UTC, mysterymath commented on llvm/test/CodeGen/MOS/instruction-selector-ir-spc700.mir
> +---
LGTM

2024-02-25 07:11 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LoImm = Builder.buildInstr(LdImm, {S8}, {}).add(MI.getOperand(1));
It hasn't been taken out; I use a temporary variable to select between `LDImmSPC700` and `LDImm` to keep the code a little bit more readable.

2024-02-25 07:12 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSInstrInfo.h
> +  void expandLDImm16SPC700(MachineIRBuilder &Builder) const;
I don't agree with the rationale presented.

First of all, if I recall my LLVM correctly, this compile stage and thus naming is internal to the compiler, and thus can be broken by us at any time without causing a breaking change to the end user. This means that, if such a future CPU appears, this name can easily be changed.

Second of all, there is precedent for logical and pseudo instructions which are specific to a given CPU to be suffixed with that CPU's name or characteristics - f.e. `PH_CMOS` and `PL_CMOS` for 65C02-specific variants of `PH` and `PL`. It helps highlight a code path as "specific to only some 6502s", rather than "available to all 6502s".

However, I do not have a strong opinion here.

2024-02-25 07:12 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSInstrInfo.cpp
> +void MOSInstrInfo::expandLDImm16SPC700(MachineIRBuilder &Builder) const {
I was conflicted on that, but have no strong opinion.

2024-02-25 07:23 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LdImm = STI.hasSPC700() ? MOS::LDImmSPC700 : MOS::LDImm;
`buildLDImm` and `buildLDImm16`, you mean?

2024-02-25 07:32 UTC, asiekierka commented on llvm/test/CodeGen/MOS/postrapseudos-spc700.mir
> +---
Thank you for the kind words.

2024-02-25 08:12 UTC, johnwbyrd commented on llvm/lib/Target/MOS/MOSInstrInfo.h
> +  void expandLDImm16SPC700(MachineIRBuilder &Builder) const;
I suppose I can risk the chance that someone will decide to implement a variant of the SPC700.

2024-02-25 08:18 UTC, mysterymath approved these changes
LGTM. Would you like to try to break out a `build` helper suite before I merge this, or should we leave exploring that until later?

2024-02-25 08:18 UTC, mysterymath commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LdImm = STI.hasSPC700() ? MOS::LDImmSPC700 : MOS::LDImm;
> `buildLDImm` and `buildLDImm16`, you mean? As each only sees one use in `MOSInstructionSelector`.

Ah, I missed the split there.

> Perhaps it's time to add a new helper file, which handles the subtarget-specific logic for building a given instruction, and refactoring away existing cases (like PH vs PH_CMOS, IN vs IN_CMOS, Inc vs IncCMOS) in that general direction?

That's part of what I've seen InstrInfo used in other target, IIRC. General helpers that use the subtarget info to build specific versions of broader logical instructions. It made sense to have all of that switching inline here when it was relatively small, but we should definitely move it out if it starts making the higher level logic here difficult to read. It could also still live in this file, probably, just out-lined.

2024-02-25 09:19 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LdImm = STI.hasSPC700() ? MOS::LDImmSPC700 : MOS::LDImm;
I see no reason to rush this PR, so I've pushed a first draft of a `MOSInstrBuilder` helper header, in line with what a few other targets do, however it's probably not idiomatic - it's mostly an extraction of stuff related to subtarget instruction selection that was previously scattered across the codebase.

2024-02-25 11:04 UTC, asiekierka commented
Having thought about it, I'd like to propose a solution to some concerns raised that should also scale well for the other operations: Having *both* an `LDImmSPC700` and an `LDImag8Imm`. In this case, the `LDImmSPC700` would act solely as a register allocator pseudo that is later expanded in post-RA into either `LDImm` (if the register being loaded into is A, X, or Y) or `LDImag8Imm` (if it's one of the imaginary registers).

The benefit here is that:

* After RA, both are treated (correctly) as distinct instructions with distinct semantics. Passes can only care about one of them without having to worry about the other, avoiding being edited whenever a new subarchitecture comes up with a new register.
* The final `MCInstLower` pass is simplified, with fewer edge cases.

@mysterymath Do you think this approach would work better/equal to the current one?

2024-02-26 01:21 UTC, mysterymath commented
> Having thought about it, I'd like to propose a solution to some concerns raised that should also scale well for the other operations: Having _both_ an `LDImmSPC700` and an `LDImag8Imm`. In this case, the `LDImmSPC700` would act solely as a register allocator pseudo that is later expanded in post-RA into either `LDImm` (if the register being loaded into is A, X, or Y) or `LDImag8Imm` (if it's one of the imaginary registers).
> 
> This is counter-intuitive, but I believe modeling _two_ instructions here will actually _simplify_ reasoning about the compiler backend. The benefit here is that:
> 
> * After RA, both are treated (correctly) as distinct instructions with distinct semantics. Passes can only care about one of them without having to worry about the other, avoiding being edited whenever a new subarchitecture comes up with a new register.
> * The final `MCInstLower` pass is simplified, with fewer edge cases.
> * We're going to have a lot more of these going forward - as suggested above, the 65CE02 and 65C816 both introduce new registers to the equation, while SPC700's additional addressing modes affect imaginary registers across six more opcodes. Even a small logic simplification is thus a big victory.
> 
> @mysterymath Do you think this approach would work better/equal to the current one?

Hmm, I don't hate it. We'd generally sought use logical instructions to regularize the instruction set, but the different targets each introduce different sets of instruction sets to regularize. The target specifications throw a wrench in thinking of it that way though: there are actually N different instructions set, and each would have its own independent regularization. I think your proposal (if I'm understanding it correctly; I may not be) is more along the lines of regularizing the joint instruction set of all targets simultaneously, which is actually what we should have been doing, since that's what we actually support in the backend.

2024-02-26 01:23 UTC, mysterymath commented on llvm/lib/Target/MOS/MOSInstrBuilder.h
> +static inline unsigned getIncOpcode(const MachineIRBuilder &Builder) {
I instantly like this a lot.

2024-03-01 19:18 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSInstructionSelector.cpp
> +  auto LdImm = STI.hasSPC700() ? MOS::LDImmSPC700 : MOS::LDImm;
Okay, after a bunch of Discord discussion I'm happy with the refactors here.

2024-03-01 19:19 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSMCInstLower.cpp
> +    if (MI->getOpcode() == MOS::LDImmSPC700) {
I found a way to divorce it altogether.

2024-03-01 19:20 UTC, asiekierka commented
After a bunch of conversations on Discord and here, I think this PR is in a good spot.

There's much more work to be done now that we have a fairly inexpensive way to vary register classes - the `Z` register on the 65CE02 and widening `A, Imag8` ALU instructions to `AImag8, Imag8` comes to mind - but I don't want to put everything in one unmergeable PR. A few steps at a time.

2024-03-02 01:18 UTC, mysterymath approved these changes

2024-03-02 01:18 UTC, mysterymath commented on llvm/lib/Target/MOS/MOSInstrPseudos.td
>    def IncCMOS : MOSPseudo {
Do we still need these? It seems like we could directly select the logical instructions `INC` and `DEC` on targets that support the 65c02 opcodes. IIRC, we should be able to break out the tablegen patterns as `Pat` definitions  with an appropriate `Predicate`.

2024-03-02 19:26 UTC, asiekierka commented on llvm/lib/Target/MOS/MOSInstrPseudos.td
>    def IncCMOS : MOSPseudo {
The thought didn't occur to me, but the latest commit should do the trick.

2024-03-02 21:42 UTC, mysterymath approved these changes

2024-03-02 21:42 UTC, merged